
import { create } from 'zustand';
import { persist } from 'zustand/middleware';

const API_URL = process.env.NEXT_PUBLIC_API_URL || '';

export interface VideoClip {
  id: string; // "Class/Filename.mp4" or "Unsorted/Filename.mp4" or "subclip-uuid"
  name: string;
  url: string; // "/api/videos/Class/Filename.mp4"
  blob?: Blob; // For new recordings
  classId: string; // "Unsorted", "Squat", etc.

  // Subclip specific - technically optional for base VideoClip, but required for Subclip type
  parentVideoId?: string;
  startTime?: number;
  endTime?: number;
  thumbnailUrl?: string;
  color?: string;
  crop?: { x: number; y: number; width: number; height: number };
  previewDirty?: boolean;
}

// Extends VideoClip to enforce subclip-specific fields
export interface Subclip extends VideoClip {
  parentVideoId: string;
  startTime: number;
  endTime: number;
}

export interface GestureClass {
  id: string;
  name: string;
  count: number;
  hasAudio: boolean;
  isDirty: boolean;
  caption: string;
  description?: string; // Generated by Gemini for Live Recognition
}

interface AppState {
  classes: GestureClass[];
  videos: VideoClip[];

  fetchDataset: () => Promise<void>;

  // Actions
  addClass: (name: string) => Promise<void>;
  addRecording: (blob: Blob) => void;
  // NEW: Add a virtual subclip
  addSubclip: (parentVideo: VideoClip, start: number, end: number, color: string, thumbnail: string, crop?: { x: number, y: number, width: number, height: number }) => string;

  deleteRecording: (id: string) => void;
  moveVideo: (videoId: string, targetClassId: string) => void;
  updateVideo: (id: string, updates: Partial<VideoClip>) => void;
  updateClass: (id: string, updates: Partial<GestureClass>) => void;
  deleteClass: (id: string) => Promise<void>;

  // Sync
  syncDataset: () => Promise<void>;
  uploadFiles: (files: File[]) => Promise<void>;
}

export const useStore = create<AppState>()(
  persist(
    (set, get) => ({
      classes: [],
      videos: [],

      fetchDataset: async () => {
        const processData = (data: any) => {
          const loadedClasses: GestureClass[] = [];
          const loadedVideos: VideoClip[] = [];

          // Handle standard scan response (Grouped Array) - from /api/videos
          if (Array.isArray(data)) {
            data.forEach((group: any) => {
              loadedClasses.push({
                id: group.id,
                name: group.name,
                count: group.count,
                hasAudio: group.hasAudio || false,
                isDirty: group.isDirty || false,
                caption: group.caption || '',
                description: group.description || ''
              });
              group.videos.forEach((vid: any) => {
                // Check if this is a subclip (has parentVideoId) or a regular video
                if (vid.parentVideoId) {
                  loadedVideos.push({
                    id: vid.id,
                    name: vid.name,
                    // For subclips, path points to parent video relative path
                    url: `${API_URL}/api/videos/${vid.path}`,
                    classId: group.id,
                    parentVideoId: vid.parentVideoId,
                    startTime: vid.startTime,
                    endTime: vid.endTime,
                    thumbnailUrl: vid.thumbnailUrl,
                    color: vid.color,
                    crop: vid.crop,
                    previewDirty: false // Assume clean on load
                  });
                } else {
                  loadedVideos.push({
                    id: vid.id,
                    name: vid.name,
                    url: `${API_URL}/api/videos/${vid.path}`,
                    classId: group.id,
                    thumbnailUrl: vid.thumbnailUrl
                  });
                }
              });
            });
          }
          // Handle raw metadata.json format (Object) - from /metadata.json
          else if (data.classes && data.sourceVideos) {
            // 1. Load Classes & Subclips
            data.classes.forEach((c: any) => {
              loadedClasses.push({
                id: c.id,
                name: c.name,
                count: 0,
                hasAudio: c.hasAudio || false,
                isDirty: c.isDirty || false,
                caption: c.caption || '',
                description: c.description || ''
              });

              if (c.subclips) {
                c.subclips.forEach((sc: any) => {
                  loadedVideos.push({
                    id: sc.id,
                    name: sc.name,
                    url: `${API_URL}/api/videos/${sc.parentVideoId}`,
                    classId: c.id,
                    parentVideoId: sc.parentVideoId,
                    startTime: sc.startTime,
                    endTime: sc.endTime,
                    thumbnailUrl: sc.thumbnailUrl,
                    color: sc.color,
                    crop: sc.crop
                  });
                });
              }
            });

            // 2. Load Source Videos
            data.sourceVideos.forEach((v: any) => {
              const parts = v.id.split('/');
              const cId = parts.length > 1 ? parts[0] : 'Unsorted';

              loadedVideos.push({
                id: v.id,
                name: v.name,
                url: `${API_URL}/api/videos/${v.path}`,
                classId: cId,
                thumbnailUrl: v.thumbnailUrl
              });
            });
          }

          // Deduplicate: If we have subclips pointing to parent videos, ensure parent videos are in loadedVideos?
          // Actually, the loop 2 adds ALL source videos. The loop 1 adds subclips.
          // We just set state.
          set({ classes: loadedClasses, videos: loadedVideos });
        };

        try {
          // 1. Fast Load from Metadata
          try {
            const metaRes = await fetch(`${API_URL}/api/videos/metadata.json`);
            if (metaRes.ok) {
              const metaData = await metaRes.json();
              processData(metaData);
            }
          } catch (e) {
            console.warn("Could not load metadata.json fast cache", e);
          }

          // 2. Authoritative Scan (Syncs disk)
          const res = await fetch(`${API_URL}/api/videos`);
          const data = await res.json();
          processData(data);

        } catch (err) {
          console.error("Failed to fetch dataset", err);
        }
      },

      addClass: async (name) => {
        try {
          const res = await fetch(`${API_URL}/api/classes`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ name })
          });
          const data = await res.json();
          if (data.success) {
            set((state) => ({
              classes: [...state.classes, {
                id: data.name,
                name: data.name,
                count: 0,
                hasAudio: false,
                isDirty: false,
                caption: ''
              }]
            }));
          }
        } catch (err) {
          console.error('Failed to add class:', err);
        }
      },

      addRecording: (blob) => {
        const url = URL.createObjectURL(blob);
        const date = new Date().toISOString().replace(/[:.]/g, '-');
        const name = `rec-${date}.webm`;

        set((state) => ({
          videos: [...state.videos, {
            id: `Unsorted/${name}`,
            name,
            url,
            blob,
            classId: 'Unsorted'
          }]
        }));
      },

      deleteRecording: (id) => set((state) => ({
        videos: state.videos.filter(r => r.id !== id)
      })),

      moveVideo: (videoId, targetClassId) => set((state) => {
        const video = state.videos.find(v => v.id === videoId);
        if (!video) return {};

        // 1. If it's a subclip, just move/reassign it
        if (video.parentVideoId) {
          return {
            videos: state.videos.map(v =>
              v.id === videoId ? { ...v, classId: targetClassId } : v
            )
          };
        }

        // 2. If it's a Source Video being "moved" to a Class (creating a reference/subclip)
        // And we ensure we aren't just moving it back to Unsorted (which does nothing for source videos usually, or reorders)
        if (targetClassId !== 'Unsorted') {
          const newSubclipId = `subclip-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
          const newClip: VideoClip = {
            id: newSubclipId,
            name: `${video.name} (Full)`,
            url: video.url,
            classId: targetClassId,
            parentVideoId: video.id, // Reference the source
            startTime: 0,
            endTime: undefined, // Indicates full length
            thumbnailUrl: video.thumbnailUrl,
            color: video.color || '#666'
          };
          // Keep the original video in Unsorted, add the new clip to the target class
          return {
            videos: [...state.videos, newClip]
          };
        }

        // 3. If dragging source video within Unsorted or back to Unsorted? 
        // Just Update classId (which is already Unsorted, but maybe we support other folders later)
        return {
          videos: state.videos.map(v =>
            v.id === videoId ? { ...v, classId: targetClassId } : v
          )
        };
      }),

      addSubclip: (parentVideo, start, end, color, thumbnail, crop) => {
        const id = `subclip-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
        // Subclips default to "Unsorted" (or same class as parent? User said "dragged to classes", implying they start unsorted or user chooses).
        // Let's put them in 'Unsorted' initially so they appear in Inbox, ready to be dragged.
        const newClip: Subclip = {
          id,
          name: `${parentVideo.name} (Clip)`, // Or allow user naming
          url: parentVideo.url,
          classId: 'Unsorted',
          parentVideoId: parentVideo.id,
          startTime: start,
          endTime: end,
          thumbnailUrl: thumbnail,
          color: color,
          crop: crop
        };
        set((state) => ({ videos: [...state.videos, newClip] }));
        return id;
      },

      updateVideo: (id, updates) => set((state) => ({
        videos: state.videos.map(v => v.id === id ? { ...v, ...updates } : v)
      })),

      updateClass: (id, updates) => set((state) => ({
        classes: state.classes.map(c => c.id === id ? { ...c, ...updates } : c)
      })),

      deleteClass: async (id: string) => {
        try {
          const res = await fetch(`${API_URL}/api/classes`, {
            method: 'DELETE',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ name: id })
          });
          const data = await res.json();
          if (data.success) {
            set((state) => ({
              classes: state.classes.filter(c => c.id !== id),
              // Unassign all videos from this class to Unsorted
              videos: state.videos.map(v =>
                v.classId === id ? { ...v, classId: 'Unsorted' } : v
              )
            }));
          }
        } catch (err) {
          console.error('Failed to delete class:', err);
        }
      },



      uploadFiles: async (files) => {
        try {
          const formData = new FormData();
          files.forEach(f => formData.append('files', f));

          const res = await fetch(`${API_URL}/api/upload`, {
            method: 'POST',
            body: formData
          });

          if (res.ok) {
            await get().fetchDataset();
          } else {
            console.error("Upload failed");
          }
        } catch (e) {
          console.error("Upload error", e);
        }
      },

      syncDataset: async () => {
        const state = get();

        // Reconstruct Metadata Structure for Backend
        // 1. Classes with Subclips
        const classesPayload = state.classes.map(c => {
          // Find subclips assigned to this class
          const subclips = state.videos.filter(v =>
            v.classId === c.id && v.parentVideoId // Must be a subclip
          ).map(sc => ({
            id: sc.id,
            parentVideoId: sc.parentVideoId,
            name: sc.name,
            startTime: sc.startTime,
            endTime: sc.endTime,
            crop: sc.crop,
            color: sc.color,
            thumbnailUrl: sc.thumbnailUrl
          }));

          return {
            id: c.id,
            name: c.name,
            description: c.description,
            subclips: subclips
          };
        });

        // 2. Source Videos (Flat List of non-subclips)
        // Actually, we should include ALL source videos known, even if they are in 'Unsorted'.
        // Subclips don't go into 'sourceVideos'.
        const sourceVideosPayload = state.videos.filter(v => !v.parentVideoId).map(v => {
          // Strip URL prefix if present to ensure relative paths in metadata
          let path = v.url;
          if (path.startsWith(API_URL)) path = path.replace(API_URL, '');
          if (path.startsWith('/api/videos/')) path = path.replace('/api/videos/', '');

          return {
            id: v.id,
            name: v.name,
            path: path
          };
        });

        const payload = {
          metadata: {
            generatedAt: new Date().toISOString(),
            version: "1.0",
            description: "Gesture Recognition Dataset with Subclips (Synced from Frontend)"
          },
          classes: classesPayload,
          sourceVideos: sourceVideosPayload
        };

        try {
          const res = await fetch(`${API_URL}/dataset/sync`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
          });
          const result = await res.json();
          if (!res.ok) throw new Error(result.error || 'Sync failed');

          // Optionally reload to confirm Sync or just alert success?
          let msg = `Sync Complete!\nCreated: ${result.stats?.created}\nDeleted: ${result.stats?.deleted}\nSkipped: ${result.stats?.skipped}\nErrors: ${result.stats?.errors}`;
          if (result.stats?.error_messages && result.stats.error_messages.length > 0) {
            msg += `\n\nError Details:\n${result.stats.error_messages.join('\n')}`;
          }
          alert(msg);

        } catch (err) {
          console.error("Sync failed", err);
          alert("Sync Failed: " + err);
        }
      },

    }),
    {
      name: 'gesture-lab-storage',
      partialize: (state) => ({
        // Persist all videos, including subclips (which have parentVideoId)
        videos: state.videos.map(v => ({
          id: v.id,
          // We need to persist standard metadata for subclips too
          classId: v.classId,
          parentVideoId: v.parentVideoId,
          startTime: v.startTime,
          endTime: v.endTime,
          thumbnailUrl: v.thumbnailUrl,
          color: v.color,
          crop: v.crop,
          name: v.name,
          previewDirty: v.previewDirty
        }))
      }),
      merge: (persistedState: any, currentState) => {
        // We need to merge loaded files from API with persisted subclips from localStorage
        // API provides the "real" files. LocalStorage provides the Subclips and the "classId" for real files (if moved).

        // This logic is tricky. Simplified approach:
        // 1. Recover subclips from LS.
        // 2. Recover classId overrides for real files from LS.
        // 3. videos list is mixture of API videos (fresh) + LS subclips.

        // Since we don't have full logic here, we rely on `fetchDataset` to populate real videos, 
        // and we just blindly accept persisted subclips?
        // A better approach in `fetchDataset`:

        return {
          ...currentState,
          // We don't restore videos here, we let fetchDataset do it, BUT we need a way to pass persisted data to it.
          // Actually, `persist` restores state BEFORE `fetchDataset` is called in component.
          // So `get().videos` in `fetchDataset` has the restored data.
          videos: persistedState.videos || []
        }
      }
    }
  )
);
